# Generated by Django 3.2.12 on 2022-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_Survival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='is_infected',
            field=models.CharField(choices=[(0, 'Non-Infected'), (1, 'Infected')], default=0, max_length=50),
        ),
    ]
