# Generated by Django 3.2.12 on 2022-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZSSN_Survival', '0003_auto_20220330_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivor',
            old_name='id',
            new_name='survivour_id',
        ),
        migrations.AlterField(
            model_name='survivor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='is_infected',
            field=models.CharField(choices=[('Non-Infected', 'Non-Infected'), ('Infected', 'Infected')], default=0, max_length=50),
        ),
    ]
